// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import types "github.com/auto-staging/builder/types"

// CloudWatchEventsModelAPI is an autogenerated mock type for the CloudWatchEventsModelAPI type
type CloudWatchEventsModelAPI struct {
	mock.Mock
}

// UpdateCloudWatchEvents provides a mock function with given fields: event
func (_m *CloudWatchEventsModelAPI) UpdateCloudWatchEvents(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// createRulesWithTarget provides a mock function with given fields: repository, branch, branchRaw, action, schedule
func (_m *CloudWatchEventsModelAPI) createRulesWithTarget(repository string, branch string, branchRaw string, action string, schedule []types.TimeSchedule) error {
	ret := _m.Called(repository, branch, branchRaw, action, schedule)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []types.TimeSchedule) error); ok {
		r0 = rf(repository, branch, branchRaw, action, schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// removeRulesWithTarget provides a mock function with given fields: repository, branch, action
func (_m *CloudWatchEventsModelAPI) removeRulesWithTarget(repository string, branch string, action string) error {
	ret := _m.Called(repository, branch, action)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repository, branch, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
