// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/auto-staging/builder/types"
)

// CodeBuildModelAPI is an autogenerated mock type for the CodeBuildModelAPI type
type CodeBuildModelAPI struct {
	mock.Mock
}

// AdaptCodeBildJobForDelete provides a mock function with given fields: event
func (_m *CodeBuildModelAPI) AdaptCodeBildJobForDelete(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdaptCodeBildJobForUpdate provides a mock function with given fields: event
func (_m *CodeBuildModelAPI) AdaptCodeBildJobForUpdate(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCodeBuildJob provides a mock function with given fields: event
func (_m *CodeBuildModelAPI) CreateCodeBuildJob(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCodeBuildJob provides a mock function with given fields: event
func (_m *CodeBuildModelAPI) DeleteCodeBuildJob(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TriggerCodeBuild provides a mock function with given fields: event
func (_m *CodeBuildModelAPI) TriggerCodeBuild(event types.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
